### ISSUE TITLE
Write mode not working

### ISSUE THREAD

**Issue by AnthonyRyuki** [xan1242/gtarctool#1]
When trying to use write mode, it always closes the application after typing "Opening & parsing" to the console. Is it a bug or is it something that wasn't yet fully implemented?

**Comment by xan1242** [comment]
It should work.

It's been a while since I've touched this tool but as far as I remember it should be able to regenerate 1:1 files to the original (minus compression).

I'll check it out and let you know...

**Comment by xan1242** [comment]
It also doesn't help that I'm using fscanf instead of a proper ini reader... I'll probably rewrite that

**Comment by AnthonyRyuki** [comment]
I tried it with more than a file, same result.
